CREATE DATABASE IF NOT EXISTS ace_admin;
USE ace_admin;

CREATE TABLE IF NOT EXISTS users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(150) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	role VARCHAR(50) DEFAULT 'admin',
	status ENUM('active','inactive') DEFAULT 'active',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS company_settings (
	id INT AUTO_INCREMENT PRIMARY KEY,
	business_name VARCHAR(150) NULL,
	logo VARCHAR(255) NULL,
	phone VARCHAR(50) NULL,
	email VARCHAR(150) NULL,
	website VARCHAR(150) NULL,
	main_address TEXT NULL,
	description TEXT NULL,
	facebook_url VARCHAR(255) NULL,
	instagram_url VARCHAR(255) NULL,
	opening_note TEXT NULL,
	status ENUM('active','inactive') DEFAULT 'active',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS branches (
	id INT AUTO_INCREMENT PRIMARY KEY,
	branch_name VARCHAR(150) NOT NULL,
	branch_code VARCHAR(50) NULL,
	full_address TEXT NOT NULL,
	area_city VARCHAR(150) NULL,
	phone VARCHAR(50) NULL,
	email VARCHAR(150) NULL,
	google_maps_link VARCHAR(500) NULL,
	opening_time TIME NULL,
	closing_time TIME NULL,
	weekly_off_day VARCHAR(50) NULL,
	branch_manager VARCHAR(150) NULL,
	status ENUM('active','inactive') DEFAULT 'active',
	notes TEXT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS service_categories (
	id INT AUTO_INCREMENT PRIMARY KEY,
	category_name VARCHAR(150) NOT NULL,
	category_slug VARCHAR(180) NOT NULL UNIQUE,
	description TEXT NULL,
	display_order INT DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS services (
	id INT AUTO_INCREMENT PRIMARY KEY,
	service_category_id INT NOT NULL,
	outlet_id INT NOT NULL,
	service_name VARCHAR(150) NOT NULL,
	service_slug VARCHAR(180) NOT NULL UNIQUE,
	description TEXT NULL,
	duration_minutes INT NOT NULL,
	price DECIMAL(10,2) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	INDEX idx_services_category (service_category_id),
	INDEX idx_services_outlet (outlet_id)
);

CREATE TABLE IF NOT EXISTS employees (
	id INT AUTO_INCREMENT PRIMARY KEY,
	outlet_id INT NOT NULL,
	employee_name VARCHAR(150) NOT NULL,
	phone VARCHAR(50) NULL,
	email VARCHAR(150) NULL,
	job_title VARCHAR(100) NULL,
	specialties TEXT NULL,
	joining_date DATE NULL,
	notes TEXT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	INDEX idx_employees_outlet (outlet_id)
);
